## Append samples of your project ##
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- production-stack_v1alpha1_staticroute.yaml
- production-stack_v1alpha1_backend.yaml
- production-stack_v1alpha1_route.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
