apiVersion: v1
kind: Secret
metadata:
  name: openai-api-key
  namespace: default
type: Opaque
data:
  # This is a placeholder value. In a real environment, replace with your actual API key (base64 encoded)
  # Example: echo -n "your-api-key" | base64
  api-key: c2stZXhhbXBsZS1vcGVuYWktYXBpLWtleQ==  # Decoded: sk-example-openai-api-key 